import = ['~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml']
# import = ['~/.config/alacritty/themes/tokyo-night/tokyo-night.toml']

[font]
size = 16

[font.bold]
family = 'SF Mono Nerd Font'
style = 'Bold'

[font.bold_italic]
family = 'SF Mono Nerd Font'
style = 'Bold Italic'

[font.italic]
family = 'SF Mono Nerd Font'
style = 'Italic'

[font.normal]
family = 'SF Mono Nerd Font'
style = 'Regular'

[window.dimensions]
columns = 120
lines = 60

[window]
opacity = 0.9
decorations = 'Full'
dynamic_title = false
title = '<3'

[window.padding]
x = 1
y = 1
